import crypto from 'node:crypto';
import { getConfig, updateConfig, seal, unseal, listWorkspaceIds } from './storage.js';
import { answerMessage } from './ai.js';

const telegramTimers=new Map();
const telegramBusy=new Set();
const cleanBase=v=>String(v||'').trim().replace(/\/+$/,'');
const graphVersion=v=>/^v\d+\.\d+$/.test(String(v||''))?String(v):'v23.0';

async function jsonFetch(url,options={}){
  const response=await fetch(url,options); const text=await response.text(); let data;
  try{data=JSON.parse(text);}catch{data={raw:text};}
  if(!response.ok||data?.ok===false||data?.error){const message=data?.description||data?.error?.message||data?.raw||`HTTP ${response.status}`;throw new Error(message);}return data;
}
export async function connectTelegram(workspaceId,payload){
  const existing=getConfig(workspaceId).channels.telegram; const botToken=String(payload.botToken||'').trim()||unseal(existing.botToken); if(!botToken)throw new Error('Bot token Telegram wajib diisi.');
  const me=await jsonFetch(`https://api.telegram.org/bot${botToken}/getMe`); const mode=payload.mode==='webhook'?'webhook':'polling'; const publicBaseUrl=cleanBase(payload.publicBaseUrl); const webhookSecret=crypto.randomBytes(18).toString('hex');
  if(mode==='webhook'){
    if(!publicBaseUrl.startsWith('https://'))throw new Error('Mode webhook membutuhkan Public HTTPS URL. Untuk local tanpa tunnel, pilih Polling.');
    await jsonFetch(`https://api.telegram.org/bot${botToken}/setWebhook`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url:`${publicBaseUrl}/webhooks/telegram/${workspaceId}/${webhookSecret}`,secret_token:webhookSecret,allowed_updates:['message','channel_post']})});
  } else await jsonFetch(`https://api.telegram.org/bot${botToken}/deleteWebhook`,{method:'POST'}).catch(()=>{});
  updateConfig(workspaceId,config=>{config.channels.telegram={...config.channels.telegram,connected:true,botToken:seal(botToken),botUsername:me.result.username||'',mode,publicBaseUrl,webhookSecret,lastUpdateId:0};});
  startTelegramPolling(workspaceId); return{username:me.result.username,mode};
}
export async function disconnectTelegram(workspaceId){const cfg=getConfig(workspaceId).channels.telegram;if(cfg.botToken)await jsonFetch(`https://api.telegram.org/bot${unseal(cfg.botToken)}/deleteWebhook`,{method:'POST'}).catch(()=>{});updateConfig(workspaceId,config=>{config.channels.telegram={...config.channels.telegram,connected:false,botToken:'',botUsername:'',webhookSecret:'',lastUpdateId:0};});stopTelegramPolling(workspaceId);}
async function telegramSend(workspaceId,chatId,text){const cfg=getConfig(workspaceId).channels.telegram;const token=unseal(cfg.botToken);if(!token)return;await jsonFetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:chatId,text})});}
export async function handleTelegramUpdate(workspaceId,update){const msg=update.message||update.channel_post;const text=msg?.text||msg?.caption;if(!msg?.chat?.id||!text)return;const answer=await answerMessage({workspaceId,message:text,sessionId:`telegram:${msg.chat.id}`,channel:'telegram'});await telegramSend(workspaceId,msg.chat.id,answer.text);}
export function stopTelegramPolling(workspaceId){const timer=telegramTimers.get(workspaceId);if(timer)clearTimeout(timer);telegramTimers.delete(workspaceId);telegramBusy.delete(workspaceId);}
export function startTelegramPolling(workspaceId){stopTelegramPolling(workspaceId);const loop=async()=>{const cfg=getConfig(workspaceId).channels.telegram;if(!cfg.connected||cfg.mode!=='polling'||!cfg.botToken)return;if(!telegramBusy.has(workspaceId)){telegramBusy.add(workspaceId);try{const token=unseal(cfg.botToken);const data=await jsonFetch(`https://api.telegram.org/bot${token}/getUpdates?timeout=0&offset=${Number(cfg.lastUpdateId||0)+1}`);for(const update of data.result||[]){await handleTelegramUpdate(workspaceId,update).catch(err=>console.error('[telegram update]',workspaceId,err.message));updateConfig(workspaceId,c=>{c.channels.telegram.lastUpdateId=update.update_id;});}}catch(err){console.error('[telegram polling]',workspaceId,err.message);}finally{telegramBusy.delete(workspaceId);}}telegramTimers.set(workspaceId,setTimeout(loop,1800));};telegramTimers.set(workspaceId,setTimeout(loop,400));}
export function startAllTelegramPolling(){for(const id of listWorkspaceIds())startTelegramPolling(id);}

export async function connectWhatsApp(workspaceId,payload){const existing=getConfig(workspaceId).channels.whatsapp;const accessToken=String(payload.accessToken||'').trim()||unseal(existing.accessToken);const phoneNumberId=String(payload.phoneNumberId||'').trim();const wabaId=String(payload.wabaId||'').trim();const version=graphVersion(payload.graphVersion);if(!accessToken||!phoneNumberId)throw new Error('Access Token dan Phone Number ID wajib diisi.');const info=await jsonFetch(`https://graph.facebook.com/${version}/${phoneNumberId}?fields=display_phone_number,verified_name`,{headers:{authorization:`Bearer ${accessToken}`}});if(wabaId)await jsonFetch(`https://graph.facebook.com/${version}/${wabaId}/subscribed_apps`,{method:'POST',headers:{authorization:`Bearer ${accessToken}`}}).catch(()=>{});updateConfig(workspaceId,config=>{config.channels.whatsapp={...config.channels.whatsapp,connected:true,accessToken:seal(accessToken),phoneNumberId,wabaId,graphVersion:version,verifyToken:String(payload.verifyToken||crypto.randomBytes(12).toString('hex')),publicBaseUrl:cleanBase(payload.publicBaseUrl)};});return info;}
export async function connectInstagram(workspaceId,payload){const existing=getConfig(workspaceId).channels.instagram;const accessToken=String(payload.accessToken||'').trim()||unseal(existing.accessToken);const igAccountId=String(payload.igAccountId||'').trim();const version=graphVersion(payload.graphVersion);if(!accessToken||!igAccountId)throw new Error('Access Token dan Instagram Account ID wajib diisi.');const info=await jsonFetch(`https://graph.instagram.com/${version}/${igAccountId}?fields=id,username,name`,{headers:{authorization:`Bearer ${accessToken}`}});updateConfig(workspaceId,config=>{config.channels.instagram={...config.channels.instagram,connected:true,accessToken:seal(accessToken),igAccountId,graphVersion:version,verifyToken:String(payload.verifyToken||crypto.randomBytes(12).toString('hex')),publicBaseUrl:cleanBase(payload.publicBaseUrl)};});return info;}
export function disconnectChannel(workspaceId,type){if(!['whatsapp','instagram'].includes(type))throw new Error('Channel tidak valid.');updateConfig(workspaceId,config=>{config.channels[type].connected=false;config.channels[type].accessToken='';});}
export function saveWebsite(workspaceId,payload){updateConfig(workspaceId,config=>{config.channels.website={...config.channels.website,connected:true,title:String(payload.title||'Maba Assistant'),welcomeMessage:String(payload.welcomeMessage||'Halo 👋 Ada yang bisa saya bantu?'),accent:String(payload.accent||'#d9ff43')};});}
export function verifyMetaWebhook(workspaceId,type,query){const cfg=getConfig(workspaceId).channels[type];const mode=query['hub.mode'];const token=query['hub.verify_token'];return mode==='subscribe'&&token&&token===cfg.verifyToken?query['hub.challenge']:null;}
async function sendWhatsApp(workspaceId,to,text){const cfg=getConfig(workspaceId).channels.whatsapp;await jsonFetch(`https://graph.facebook.com/${graphVersion(cfg.graphVersion)}/${cfg.phoneNumberId}/messages`,{method:'POST',headers:{authorization:`Bearer ${unseal(cfg.accessToken)}`,'content-type':'application/json'},body:JSON.stringify({messaging_product:'whatsapp',recipient_type:'individual',to,type:'text',text:{preview_url:false,body:text}})});}
export async function handleWhatsAppWebhook(workspaceId,body){const values=body?.entry?.flatMap(e=>e.changes||[]).map(c=>c.value)||[];for(const value of values){for(const msg of value.messages||[]){const text=msg.text?.body;if(!text||!msg.from)continue;const answer=await answerMessage({workspaceId,message:text,sessionId:`whatsapp:${msg.from}`,channel:'whatsapp'});await sendWhatsApp(workspaceId,msg.from,answer.text);}}}
async function sendInstagram(workspaceId,recipientId,text){const cfg=getConfig(workspaceId).channels.instagram;await jsonFetch(`https://graph.instagram.com/${graphVersion(cfg.graphVersion)}/${cfg.igAccountId}/messages`,{method:'POST',headers:{authorization:`Bearer ${unseal(cfg.accessToken)}`,'content-type':'application/json'},body:JSON.stringify({recipient:{id:recipientId},message:{text}})});}
export async function handleInstagramWebhook(workspaceId,body){for(const entry of body?.entry||[]){for(const event of entry.messaging||[]){const sender=event.sender?.id;const text=event.message?.text;if(!sender||!text||event.message?.is_echo)continue;const answer=await answerMessage({workspaceId,message:text,sessionId:`instagram:${sender}`,channel:'instagram'});await sendInstagram(workspaceId,sender,answer.text);}}}
export async function sendHumanReply(workspaceId,conversation,text){if(conversation.channel==='telegram')return telegramSend(workspaceId,conversation.sessionId.split(':').slice(1).join(':'),text);if(conversation.channel==='whatsapp')return sendWhatsApp(workspaceId,conversation.sessionId.split(':').slice(1).join(':'),text);if(conversation.channel==='instagram')return sendInstagram(workspaceId,conversation.sessionId.split(':').slice(1).join(':'),text);return true;}
